server:
  port: 8080
spring:
  application:
    name: springboot-shop-prod
  datasource:
    url: jdbc-secretsmanager:mysql://${DB_ENDPOINT}:3306/shop
    username: prod/shop/mysql-8.x
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver

  redis:
    host: ${REDIS_ENDPOINT}
    port: 6379

tracing:
  url: http://${EKS_MYSQL_EXPORTER}:4318/v1/traces

logging.level.root : info

msa.service.endpoint.benefit: ${BENEFIT_SERVICE_ENDPOINT}
msa.service.endpoint.prod : ${PROD_SERVICE_ENDPOINT}
msa.service.endpoint.point: ${POINT_SERVICE_ENDPOINT}